# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c157e42c196fec01fd4313141af992e1782da418cd222ce2db5ad40ff24184ce0104ca6a1ea7f084b9a2049e84c4f279093d671e58206c38741affe51695aab9

test:
  secret_key_base: d6162551d144c5806b29c71d38e36d97e9bd6ec643bcec02e45c58b26285ef5af8ebb0018a78671ba3e32311c0f3a1d92b4fa63c658b7850975537cd9a2a69a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
